language: node_js

node_js:
 - "8"
 - "10"
 - "12"

sudo: false

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11

after_success:
 - if [[ ${TRAVIS_NODE_VERSION} == "0.10" ]]; then npm run coverage; fi;